language: ruby

cache: bundler

services:
  - redis-server

rvm:
  - 2.6.3

sudo: false

env:
  global:
    - REDIS_HOST=localhost
    - REDIS_PORT=6379
    - REDIS_DB=1

install:
  - bin/setup

script: rake spec